FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Game.RoomService/Game.RoomService.csproj", "Game.RoomService/"]
COPY ["Game.Shared/Game.Shared.csproj", "Game.Shared/"]
RUN dotnet restore "Game.RoomService/Game.RoomService.csproj"
COPY . .
WORKDIR "/src/Game.RoomService"
RUN dotnet build "Game.RoomService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Game.RoomService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Game.RoomService.dll"]