FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["src/Game.ApiGateway/Game.ApiGateway.csproj", "src/Game.ApiGateway/"]
COPY ["shared/Game.Shared/Game.Shared.csproj", "shared/Game.Shared/"]
RUN dotnet restore "src/Game.ApiGateway/Game.ApiGateway.csproj"
COPY . .
WORKDIR "/src/src/Game.ApiGateway"
RUN dotnet build "Game.ApiGateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Game.ApiGateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Game.ApiGateway.dll"]