FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Game.AuthService/Game.AuthService.csproj", "Game.AuthService/"]
COPY ["Game.Shared/Game.Shared.csproj", "Game.Shared/"]
RUN dotnet restore "Game.AuthService/Game.AuthService.csproj"
COPY . .
WORKDIR "/src/Game.AuthService"
RUN dotnet build "Game.AuthService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Game.AuthService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Game.AuthService.dll"]