FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["Game.GameService/Game.GameService.csproj", "Game.GameService/"]
COPY ["Game.Shared/Game.Shared.csproj", "Game.Shared/"]
RUN dotnet restore "Game.GameService/Game.GameService.csproj"
COPY . .
WORKDIR "/src/Game.GameService"
RUN dotnet build "Game.GameService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Game.GameService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Game.GameService.dll"]