<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Consul" Version="1.7.14.5" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.2.0" />
    <PackageReference Include="Microsoft.Orleans.Client" Version="8.2.0" />
    <PackageReference Include="MemoryPack" Version="1.10.0" />
    <PackageReference Include="Ocelot" Version="23.4.2" />
    <PackageReference Include="Ocelot.Provider.Consul" Version="23.4.2" />
    <PackageReference Include="OpenTelemetry" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.5.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Game.Shared\Game.Shared.csproj" />
  </ItemGroup>

</Project>
